In [1]:
import numpy as np


In [2]:
np.__version__

'1.20.1'

array created using numpy will convert all of its elements in single data type 

with precedence string>float>int


In [3]:
arr=np.array([1,3,5,7.9,2])
arr

array([1. , 3. , 5. , 7.9, 2. ])

In [7]:
arr=np.arange(0,11)# given parameters are start and stop can also give increment
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr=np.linspace(1,18,6)#Generating  numbers between two intervals by giving length 
arr

array([ 1. ,  4.4,  7.8, 11.2, 14.6, 18. ])

In [18]:
arr=np.zeros(7,dtype=int)#Generating 7 length array filled with zeros
arr

array([0, 0, 0, 0, 0, 0, 0])

In [20]:
arr=np.ones((3,4),dtype=int)#Generating 3x4 shape array filled with ones
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.full((3,3),4)#filled with our our required number 

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [63]:
np.random.randint(1999)# here range is given from 0 to 1998 so it will generate any number

1436

In [37]:
np.random.randint(-10,10,(3,3))#Generates random values between given intervals(first interval inclusive second exclusive)
#np.random.randint(-10,10,size=(3,3)) can use this  also
#np.random.randint(5,size=(4,2,3)) #four matrix of 2x3 

array([[ -7,   7,   2],
       [ -7,  -6,  -6],
       [-10,  -6,  -4]])

In [26]:
np.random.normal(5,1,9)
# it will generate nine numbers by fulfulling the condition that there mean will be 5 and their standard deviation will be 1

array([5.54120518, 4.80753483, 4.01781226, 4.84661033, 3.55120557,
       6.03156735, 6.11262251, 3.36739182, 4.1716393 ])

In [48]:
np.eye(3)#Identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.random.random(size=(2,2))#returns a floating point number in the range [0.0, 1.0) :which means 0.0 is possible but 1.0 isnt 

array([[0.51300854, 0.51516928],
       [0.57863104, 0.89946294]])

### Dimension shape and size


In [21]:
array=np.random.random((3,2))
print(array)

[[0.51093885 0.63816371]
 [0.03953864 0.84203203]
 [0.32783315 0.33309129]]


In [22]:
array.shape#tell us about the order

(3, 2)

In [24]:
#reshape your array
array.reshape(6)
# array.reshape(2,3)


array([0.51093885, 0.63816371, 0.03953864, 0.84203203, 0.32783315,
       0.33309129])

In [68]:
array.ndim#tell us the dimension like 2d array or 3d

2

In [69]:
array.size# size of array 2*3=6

6

In [124]:
# hell=np.random.randint(23,size=(4,3,2))#3d array
hell=np.arange(24).reshape((4,3,2))# creating 3d array 
#one thing to note here if you are giving arange your desired reshape than you have to give exact space to fill all the numbers
#spaces

In [125]:
hell#rgb colour is the example/application of 3d array 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [126]:
#acessing 3d array elements 
#access number 14
hell[2][1][0]#first we are giving z=matrix number then x=row then y=coloumn 

14

In [135]:
array=np.arange(12).reshape(3,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
array.max(axis=0)


array([ 8,  9, 10, 11])

In [12]:
x=np.array([[2,3],[4,5]])
y=np.array([[2,3],[4,5]])


In [13]:
x.dot(y)#It is multplying 2 matrices

array([[16, 21],
       [28, 37]])

In [14]:
y[0:2,1]

array([3, 5])